USE GD2C2020
GO
 	
	DROP PROCEDURE GDD.CREAR_DIMENSIONES
	DROP PROCEDURE GDD.CREAR_HECHOS
	DROP PROCEDURE GDD.CREAR_PK
	DROP PROCEDURE GDD.CREAR_FK
	DROP PROCEDURE GDD.CARGAR_DIMENSIONES
	DROP PROCEDURE GDD.CARGAR_HECHOS_AUTOMOVILES
	DROP PROCEDURE GDD.CARGAR_HECHOS_AUTO_PARTES

	DROP TABLE GDD.BI_Fact_Compra_Automoviles

	DROP TABLE GDD.BI_Fact_Ventas_Automoviles

	DROP TABLE GDD.BI_Fact_Compra_Auto_Partes

	DROP TABLE GDD.BI_Fact_Ventas_Auto_Partes
	

	DROP TABLE GDD.BI_Dim_Tiempo

	DROP TABLE GDD.BI_Dim_Cliente

	DROP TABLE GDD.BI_Dim_Sucursal

	DROP TABLE GDD.BI_Dim_Modelo

	DROP TABLE GDD.BI_Dim_Fabricante

	DROP TABLE GDD.BI_Dim_TipoAutomovil

	DROP TABLE GDD.BI_Dim_TipoCajaCambios

	--TODO
	--DROP TABLE BI_GDD.Dim_CantidadCambios

	DROP TABLE GDD.BI_Dim_TipoMotor

	DROP TABLE GDD.BI_Dim_TipoTransmision

	DROP TABLE GDD.BI_Dim_Potencia

	DROP TABLE GDD.BI_Dim_AutoParte

	--TODO
	--DROP TABLE GDD.BI_Dim_RubroAutoParte


	DROP FUNCTION GDD.CALCULAR_EDAD
	DROP FUNCTION GDD.CALCULAR_RANGO_EDAD
	DROP FUNCTION GDD.CALCULAR_POTENCIA

